#pragma once

#define STAT_WISP_VERSION_MAJOR 0
#define STAT_WISP_VERSION_MINOR 4
#define STAT_WISP_VERSION_PATCH 1
#define STAT_WISP_VERSION_STRING "0.4.1"
#define STAT_WISP_VERSION_WSTRING L"0.4.1"
